spring:
  application:
    name: eureka-server
    hostname: 192.168.1.110
#一个tomcat部署多个项目需指定domain    
  jmx:
    default-domain: eureka-server-domain
    
#服务注册中心端口号
server:
  port: 8080

#服务注册中心实例的主机名
eureka:
  instance:
    hostname: ${spring.application.hostname}
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务
    serviceUrl:
    #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${spring.application.hostname}:${server.port}/spring-eureka/eureka/

security:
  user:
    name: admin
    password: a123456
    

    
    