#服务名称
spring:
  application:
    name: spring-web
    hostname: 192.168.1.110
  #一个tomcat部署多个项目需指定domain    
  jmx:
    default-domain: spring-web-domain
    
#端口号
server:
  port: 2003
  
beetl:
  templatesPath: /WEB-INF/views/ #classpath:
  prefix: /WEB-INF/views/
  suffix: .html

    
#Mybatis  
#mybatis:
#  config-locations: classpath:mybatis/mybatis-config.xml  
#  mapper-locations: classpath:mybatis/mapper/*.xml  
#  mybatis.type-aliases-package: com.damionew.website.model  

    

 
  

