#服务名称
spring:
  application:
    name: spring-web

 #端口号
server:
  port: 2003
  
beetl:
  templatesPath: /WEB-INF/views/ #classpath:
  prefix: /WEB-INF/views/
  suffix: .html

    
#Mybatis  
#mybatis:
#  config-locations: classpath:mybatis/mybatis-config.xml  
#  mapper-locations: classpath:mybatis/mapper/*.xml  
#  mybatis.type-aliases-package: com.damionew.website.model  

    

 
  

