#服务名称
spring:
  application:
    name: spring-api
    hostname: 192.168.253.110
#一个tomcat部署多个项目需指定domain    
  jmx:
    default-domain: spring-api-domain
    
#服务注册中心实例的主机名
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress: true
    #appname: spring-api
    #homePageUrlPath: /spring-api
                
 #端口号
server:
  port: 9001
 
