spring:
  application:
    name: eureka-server-253-110

#服务注册中心端口号
server:
  port: 8080

#服务注册中心实例的主机名
eureka:
  instance:
    hostname: 192.168.253.110
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务
    serviceUrl:
    #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/spring-eureka/eureka/

security:
  user:
    name: admin
    password: a123456
    

    
    